
package View;

import Model.Cliente;
import Model.Pet;
import Model.Procedimento;
import Model.Produto;
import java.util.ArrayList;

/**
 *
 * @author isabe
 */
public class Atendimento extends javax.swing.JFrame {

    private ArrayList<Model.Atendimento> atendimento = new ArrayList<>();
    private ArrayList<Cliente> cliente = new ArrayList<>();
    private ArrayList<Pet> pet = new ArrayList<>();
    private ArrayList<Produto> produto = new ArrayList<>();
    private ArrayList<Procedimento> procedimento = new ArrayList<>();
   
    public Atendimento() {
        initComponents();
        pet.setOpaque(false);
        pet.setBackground(new java.awt.Color(0,0,0,1));
        cliente.setOpaque(false);
        cliente.setBackground(new java.awt.Color(0,0,0,1));
        procedimento.setOpaque(false);
        procedimento.setBackground(new java.awt.Color(0,0,0,1));
        produto.setOpaque(false);
        produto.setBackground(new java.awt.Color(0,0,0,1));
        data.setOpaque(false);
        data.setBackground(new java.awt.Color(0,0,0,1));
         
         data.setText(String.valueOf("MOSTRAR TEXTO"));
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        voltar = new javax.swing.JButton();
        data = new javax.swing.JTextField();
        produto = new javax.swing.JTextField();
        procedimento = new javax.swing.JTextField();
        pet = new javax.swing.JTextField();
        cliente = new javax.swing.JTextField();
        confirma = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PetPlus - Cadastro de Atendimento\n");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        voltar.setBorder(null);
        voltar.setBorderPainted(false);
        voltar.setContentAreaFilled(false);
        voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 530, 120, 30));

        data.setBackground(new java.awt.Color(242, 242, 242));
        data.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        data.setBorder(null);
        data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataActionPerformed(evt);
            }
        });
        getContentPane().add(data, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, 400, 40));

        produto.setBackground(new java.awt.Color(242, 242, 242));
        produto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        produto.setBorder(null);
        produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtoActionPerformed(evt);
            }
        });
        getContentPane().add(produto, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 370, 40));

        procedimento.setBackground(new java.awt.Color(242, 242, 242));
        procedimento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        procedimento.setBorder(null);
        procedimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procedimentoActionPerformed(evt);
            }
        });
        getContentPane().add(procedimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 320, 40));

        pet.setBackground(new java.awt.Color(242, 242, 242));
        pet.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pet.setBorder(null);
        pet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petActionPerformed(evt);
            }
        });
        getContentPane().add(pet, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 420, 40));

        cliente.setBackground(new java.awt.Color(242, 242, 242));
        cliente.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        cliente.setBorder(null);
        cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteActionPerformed(evt);
            }
        });
        getContentPane().add(cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 380, 40));

        confirma.setBorder(null);
        confirma.setContentAreaFilled(false);
        confirma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        confirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmaActionPerformed(evt);
            }
        });
        getContentPane().add(confirma, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 530, 110, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/atendimento.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void petActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petActionPerformed

    private void clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteActionPerformed

    private void procedimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procedimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_procedimentoActionPerformed

    private void confirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmaActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_voltarActionPerformed

    private void produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_produtoActionPerformed

    private void dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Atendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Atendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Atendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Atendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Atendimento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cliente;
    private javax.swing.JButton confirma;
    private javax.swing.JTextField data;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField pet;
    private javax.swing.JTextField procedimento;
    private javax.swing.JTextField produto;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
