
package View;

import Model.Atendimento;
import Model.Cliente;
import Model.Pet;
import Model.Procedimento;
import Model.Produto;
import java.util.ArrayList;
import javax.swing.JOptionPane;


public class cadastroPet extends javax.swing.JFrame {

    private ArrayList<Atendimento> atendimento = new ArrayList<>();
    private ArrayList<Cliente> cliente = new ArrayList<>();
    private ArrayList<Pet> pet = new ArrayList<>();
    private ArrayList<Produto> produto = new ArrayList<>();
    private ArrayList<Procedimento> procedimento = new ArrayList<>();
    
    
    public cadastroPet(ArrayList<Atendimento> atendimento, ArrayList<Cliente> cliente, ArrayList<Pet> pet, ArrayList<Produto> produto, ArrayList<Procedimento> procedimento) {
        
        initComponents();
        
        this.atendimento = atendimento;
        this.cliente = cliente;
        this.pet = pet;
        this.produto = produto;
        this.procedimento = procedimento;
        
        dono.setOpaque(false);
        dono.setBackground(new java.awt.Color(0,0,0,1));
        especie.setOpaque(false);
        especie.setBackground(new java.awt.Color(0,0,0,1));
        sexo.setOpaque(false);
        sexo.setBackground(new java.awt.Color(0,0,0,1));
        idade.setOpaque(false);
        idade.setBackground(new java.awt.Color(0,0,0,1));
        nome.setOpaque(false);
        nome.setBackground(new java.awt.Color(0,0,0,1));
    }
    
    private cadastroPet() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dono = new javax.swing.JTextField();
        especie = new javax.swing.JTextField();
        sexo = new javax.swing.JTextField();
        idade = new javax.swing.JTextField();
        nome = new javax.swing.JTextField();
        apagar = new javax.swing.JButton();
        confirma = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PetPlus - Cadastro de Pet\n");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dono.setBackground(new java.awt.Color(242, 242, 242));
        dono.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        dono.setBorder(null);
        dono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donoActionPerformed(evt);
            }
        });
        getContentPane().add(dono, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, 380, 40));

        especie.setBackground(new java.awt.Color(242, 242, 242));
        especie.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        especie.setBorder(null);
        especie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especieActionPerformed(evt);
            }
        });
        getContentPane().add(especie, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 260, 40));

        sexo.setBackground(new java.awt.Color(242, 242, 242));
        sexo.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        sexo.setBorder(null);
        sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoActionPerformed(evt);
            }
        });
        getContentPane().add(sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 380, 40));

        idade.setBackground(new java.awt.Color(242, 242, 242));
        idade.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        idade.setBorder(null);
        idade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idadeActionPerformed(evt);
            }
        });
        getContentPane().add(idade, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 120, 40));

        nome.setBackground(new java.awt.Color(242, 242, 242));
        nome.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        nome.setBorder(null);
        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        getContentPane().add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 380, 40));

        apagar.setBorder(null);
        apagar.setBorderPainted(false);
        apagar.setContentAreaFilled(false);
        apagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagarActionPerformed(evt);
            }
        });
        getContentPane().add(apagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 520, 130, 40));

        confirma.setBorder(null);
        confirma.setBorderPainted(false);
        confirma.setContentAreaFilled(false);
        confirma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        confirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmaActionPerformed(evt);
            }
        });
        getContentPane().add(confirma, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 520, 130, 40));

        voltar.setBorder(null);
        voltar.setBorderPainted(false);
        voltar.setContentAreaFilled(false);
        voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 520, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cadastroPet.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void donoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_donoActionPerformed

    private void especieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_especieActionPerformed

    private void sexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexoActionPerformed

    private void idadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idadeActionPerformed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagarActionPerformed
         String t = "";
        sexo.setText(t);
        nome.setText(t);
        idade.setText(t);
        especie.setText(t);
        
        dono.setEnabled(true);
        this.confirma.setEnabled(true);
    }//GEN-LAST:event_apagarActionPerformed

    private void confirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmaActionPerformed
    if (!(nome.getText().isEmpty() || dono.getText().isEmpty() || sexo.getText().isEmpty() || especie.getText().isEmpty() || idade.getText().isEmpty())) {
            //Verifica se tem o dono na lista de cliente
            Cliente atual = null;
            boolean achou = false;
            for (int x = 0; x < cliente.size(); x++) {
                if (cliente.get(x).getNome().equalsIgnoreCase(dono.getText())) {
                    achou = true;
                    atual = cliente.get(x);
                    break;
                }
            }
            if (achou) {
                pet.add(new Pet(atual, nome.getText(), especie.getText(), sexo.getText()));
                String t = "";
                dono.setText(t);
                nome.setText(t);
                especie.setText(t);
                sexo.setText(t);
                
                
                JOptionPane.showMessageDialog(this, "Pet cadastrado!", "CADASTRO", JOptionPane.INFORMATION_MESSAGE);
                
            } else {
                JOptionPane.showMessageDialog(this, "Dono do PET não é um cliente\ncadastrado no sistema!", "NÃO CADASTRADO", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Favor preencher todos os campos", "VAZIO", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_confirmaActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        Menu tela = new Menu(atendimento, cliente, pet, produto, procedimento);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroPet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton apagar;
    private javax.swing.JButton confirma;
    private javax.swing.JTextField dono;
    private javax.swing.JTextField especie;
    private javax.swing.JTextField idade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField sexo;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
